
remote_theme: mmistakes/so-simple-theme@3.2.0
skin: "/assets/css/skins/dark.css"
locale: en-US
title: "What's Prerna Cooking"
description: "A Pandemic-Induced Recipe Website"
baseurl: # the subpath of your site, e.g. "/blog"
url: http://prernaadvani.github.io
logo: https://raw.githubusercontent.com/prernaadvani/prernaadvani.github.io.temp/master/images/IMG_0466.jpg
date_format: "%B %-d, %Y"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

disqus:
  shortname: prernaadvani
twitter:
  username: prerna206

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml


paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Prerna Advani
  picture: https://raw.githubusercontent.com/prernaadvani/prernaadvani.github.io.temp/master/images/IMG_0466.jpg
  email: prerna206@hotmail.com
  twitter: prerna206
  links:
    - title: Email
      url: mailto:prerna206@hotmail.com
      icon: fas fa-envelope

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/prerna206
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/prernaadvani/
    icon: fab fa-linkedin
  - title: Email
    url: mailto:prerna206@hotmail.com
    icon: fas fa-envelope
  
 
copyright: ""
